#This file contains the default settings every player will get, when he uses the plugin for the first time.
enabled: true

Arrow:
    particle: CRIT
    color: red
    enabled: true
    distance-level: 1
Snowball:
    particle: CRIT
    color: blue
    enabled: true
    distance-level: 1
Enderpearl:
    particle: CRIT
    color: purple
    enabled: true
    distance-level: 1
Egg:
    particle: CRIT
    color: white
    enabled: true
    distance-level: 1
Potion:
    particle: CRIT
    color: green
    enabled: true
    distance-level: 0